name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
commitish: main
category-template: "### $TITLE"
categories:
  - title: "Enhancement"
    when:
      label: "enhancement"
  - title: "Fixes"
    when:
      label: "fix"
  - title: "Chore"
    when:
      label: "chore"
  - type: "version-resolver"
    semver-increment: "major"
    when:
      label: "major"
  - type: "version-resolver"
    semver-increment: "minor"
    when:
      label: "minor"
  - type: "version-resolver"
    semver-increment: "patch"
    when:
      label: "patch"
  - type: "version-resolver"
    semver-increment: "patch"
change-template: "- $TITLE (#$NUMBER)"
change-title-escapes: '\<*_&'
autolabeler:
  - label: "patch"
    title:
      - "/^patch:/i"
  - label: "minor"
    title:
      - "/^minor:/i"
  - label: "major"
    title:
      - "/^major:/i"
  - label: "enhancement"
    title:
      - "/^feat:/i"
      - "/^feature:/i"
      - "/^enhancement:/i"
  - label: "fix"
    title:
      - "/^fix:/i"
      - "/^bugfix:/i"
  - label: "chore"
    title:
      - "/^chore:/i"
      - "/^docs:/i"
      - "/^refactor:/i"
      - "/^test:/i"
      - "/^ci:/i"
template: |
  ## Changes

  $CHANGES

  ### Summary

  <!-- spai:release-summary:start -->
  - 요약할 변경사항이 없습니다.
  <!-- spai:release-summary:end -->

  ### Contributors

  $CONTRIBUTORS
